name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Make and run the library in Release mode
      run: |
        cd red-black-tree
        mkdir Release
        cd Release
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
        ./rbtree
        
    - name: Make and run the library in Debug mode
      run: |
        cd red-black-tree
        mkdir Debug
        cd Debug
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        make
        ./rbtree
